"""empty message

Revision ID: 0dba8a6b6bbe
Revises: 293ba3bae55f
Create Date: 2021-06-02 11:39:48.557757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dba8a6b6bbe'
down_revision = '293ba3bae55f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_username_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    # ### end Alembic commands ###
