"""empty message

Revision ID: 1513b259d3fa
Revises: e2b5fec44838
Create Date: 2021-05-31 15:19:13.302999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1513b259d3fa'
down_revision = 'e2b5fec44838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profile', 'currency', ['currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'currency_id')
    # ### end Alembic commands ###
