"""empty message

Revision ID: 3618502fac70
Revises: 1513b259d3fa
Create Date: 2021-05-31 15:39:52.335968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3618502fac70'
down_revision = '1513b259d3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
